apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-platform-staging
resources:
- ../../base
namePrefix: staging-
images:
- name: ghcr.io/jbluemel/dbt-postgres
  newTag: 1.0.30
