apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - dbt-secret.yaml
  - dbt-cronjob.yaml